[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Николай Ануфриев <sch-nikolaj@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
